#!/bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

#status bar (polybar)
killall -q polybar
polybar -r my-bar &

# use feh for background
#feh --no-fehbg --bg-scale '/home/hendrik/Bilder/backgrounds/stars_space_nebula_141264_1920x1080.jpg' &

feh --no-fehbg --bg-scale '/home/hmaier/Bilder/backgrounds/morrowind_pic.jpeg' &

# for java applications
wmname LG3D &

# start compositor for transparency
#picom &

# declaring the differnt workspaces
#bspc monitor -d I II III IV V VI VII VIII #### comment 9 and 10 out IX X
bspc monitor -d 1 2 3 4 5 
#bspc monitor -d web 2 3 4 steam 

bspc config border_width         5
bspc config window_gap           20

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Steam desktop='^5' state=floating
bspc rule -a Freundesliste desktop='^5' state=pseudo_tiled
bspc rule -a Evince state=floating
bspc rule -a Viewnior state=floating
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Pycalendar.py state=floating rectangle=600x400+660+100_
bspc rule -a Zathura state=tiled
bspc rule -a Android-Studio state=tiled
bspc rule -a OpenMW state=fullscreen

#----------------------------
#Auto Start Programms
#----------------------------
syncthing -no-browser &
