#!/bin/sh
#------------------------------------------------------------------------------------
# BSPWM
#------------------------------------------------------------------------------------
pgrep -x sxhkd > /dev/null || sxhkd &

#status bar (polybar)
killall -q polybar
polybar --config-file="$HOME/.config/polybar/config.ini" -r center_bar &

# use feh for background
bg=$(cat $HOME/Bilder/backgrounds/.active-background.txt)
feh --no-fehbg --bg-scale "$bg" &

# for java applications
wmname LG3D &

# start compositor for transparency
#picom &

# turning on the numpad
numlockx on &

# change cursor for X
xsetroot -cursor_name left_ptr &

# setting keyboard DELAY (when pressing button) and SPEED (of how many chars are typed per second)
xset r rate 200 30 &

# declaring the differnt workspaces
#bspc monitor -d I II III IV V VI VII VIII #### comment 9 and 10 out IX X
bspc monitor -d 1 2 3 4 5 6
#bspc monitor -d web 2 3 4 steam 

bspc config border_width         3
bspc config window_gap           10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focus_follows_pointer false
bspc config focused_border_color '#EEEEE'

bspc config automatic_scheme longest_side

bspc rule -a Evince state=floating
bspc rule -a Viewnior state=floating
bspc rule -a Screenkey manage=off
bspc rule -a Zathura state=floating
bspc rule -a "feh"  state=floating 

bspc rule -a "jetbrains-phpstorm" desktop='^1' state=floating
bspc rule -a "brave-browser" desktop='^2' state=tiled
bspc rule -a "minecraft-launcher" desktop='^4' state=tiled
bspc rule -a Steam desktop='^5' state=floating
#bspc rule -a "Remmina Remote-Desktop Client" desktop='^5' state=pseudo_tiled rectangle=900x500+500+800_

#----------------------------
#Auto Start Programms
#----------------------------

# home pc
if [[ $HOSTNAME -eq "wooden-arch-box" ]]; then
	syncthing -no-browser & # reach gui on localhost:8384
fi

# work pc
if [[ $HOSTNAME -eq "azt-4329" ]]; then
	remmina & # replace this with a script
	bspc node -d '^5'
	brave &
	bspc node -d '^1'
	xfce4-terminal &			
	bspc node -d '^2'
fi



