#!/bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

#status bar (polybar)
killall -q polybar
polybar -r my-bar &

# use feh for background
#feh --no-fehbg --bg-scale '/home/hendrik/Bilder/backgrounds/stars_space_nebula_141264_1920x1080.jpg' &
bg=$(cat '/home/$USER/Bilder/backgrounds/.active-background')
feh --no-fehbg --bg-scale $bg &

# for java applications
wmname LG3D &

# start compositor for transparency
#picom &

# turning on the numpad
numlockx on &

# declaring the differnt workspaces
#bspc monitor -d I II III IV V VI VII VIII #### comment 9 and 10 out IX X
bspc monitor -d 1 2 3 4 5 
#bspc monitor -d web 2 3 4 steam 

bspc config border_width         3
bspc config window_gap           10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focus_follows_pointer false
bspc config focused_border_color '#40E0D0'

bspc config automatic_scheme spiral

bspc rule -a Evince state=floating
bspc rule -a Viewnior state=floating
bspc rule -a Screenkey manage=off
bspc rule -a Pycalendar.py state=floating rectangle=600x400+660+100_
bspc rule -a Zathura state=tiled
bspc rule -a Android-Studio state=tiled

bspc rule -a "jetbrains-phpstorm" desktop='^1' state=floating
bspc rule -a "brave-browser" desktop='^2' state=tiled
bspc rule -a "minecraft-launcher" desktop='^4' state=tiled
bspc rule -a Steam desktop='^5' state=floating
bspc rule -a "Remmina Remote-Desktop Client" desktop='^5' state=tiled

#----------------------------
#Auto Start Programms
#----------------------------

# home pc
if [[ $HOSTNAME -eq "wooden-arch-box" ]]; then
	syncthing -no-browser &
	steam &
fi

# work pc
if [[ $HOSTNAME -eq "azt-4329" ]]; then
	remmina &
fi
